### ISSUE TITLE
Updater Loading Too Long

### ISSUE THREAD

**Issue by LiberteIV** [ltGuillaume/LibreWolf-WinUpdater#14]
This might not really be an issue but it is a bit annoying.
The LibreWolf WinUpdater took around 4-6 minutes to finish its update process, i was monitoring the taskmanager and the time.
I had no applications running so nothing used any bandwith.
Why does the updater take so long? Updates in firefox are much faster, almost instantly.

Please dont take this critic badly, its just my opinion. I hope that future version of the updater will provide increased speed downloading/updating the librewolf browser.
Unless it is intended to "take its time" with the update, would you explain why it takes that long?
Should just be a few MB/s ?

**Comment by ltGuillaume** [comment]
- It downloads as fast as possible from Gitlab, there might be a routing issue for you that causes slow downloads
- Portable version: it only replaces the files in the target folder that have actually been changed. In order to do that, files with the same size are hashed and compared to the new version. This might take a bit more time. (This is done to decrease the amount of writes on removable media, such as USB sticks.)
- After a successful update, the updater will sleep for 60 seconds, so that the notification of the update will stay in the Action Center for a while.

**Comment by LiberteIV** [comment]
1. Using and updating both version.
2. I ran the updater with schedule task and manually (it's both the same slow)

I don't think i have routing issues because streaming and gaming and upload/download works normally with good speed.
Is it not possible to create a windows notification alert that the update was successful instead of sleeping a minute?
For me it is always a burden with the slow updater because i need to wait for it to dissapear from the taskmanager, otherwise if i start the browser the update will not be completed?

**Comment by ltGuillaume** [comment]
Routing issues can be related to/cause slow traffic for a single website. Try downloading an old, release, e.g. https://gitlab.com/librewolf-community/browser/windows/uploads/94300fb0fcdb78865f3cfed8ca6f498b/librewolf-103.0.1-2.en-US.win64-portable.zip and see how long it takes.

> Is it not possible to create a windows notification alert that the update was successful instead of sleeping a minute?

No, the notification disappears when the application closes. But why would it be an issue if the updater would sit for a minute?

Why would you want to wait for it in the Task Manager? The update is finished as soon as the notification pops up.

**Comment by LiberteIV** [comment]
I can only saw so much that i don't have any speed issues with any website or application.
Tought that it is normal behaviour for librewinupdater to take 4-6 minuites, is it not?
I can't tell how much time the program actually needs to finish downloading new releases, that's because it stays in taskmanager even after it's finish as you said, but if that is exactly 60 seconds then the updater would still take 2-4 minutes, which is not a long period of time but considering how smal the packet size must be for a single update it is a long time.
So the 60 seconds is not an issue for me, but when i open librewolf while the updater is still active it says error finishing update, launch the interactive installer now, so what bothers me is only that i must wait before i can use the browser.
When i start my system the first thing i normally do is opening browser, but the schedule task to check for updates is always present after boot, and portable version will always start the updater when the browser is opened, so in both cases i must wait before i can do anything.
Sorry i dont know what you mean by overflow menu and i dont get any popups/notifications from the updater in general as far as i remember, it is only visible in task manager doing its thing and silently updating librewolf.

**Comment by ltGuillaume** [comment]
It should take no more than 30 seconds, depending on the download speed of course. That's why I wanted to know how long the provided link would take you to download.

A single update is always the entire size of a LibreWolf release, which is between 100 (zip) and 125 (exe) megabytes.

That's a significant download, so your connection speed and the specific routing to Gitlab is of importance.

Only if you run LibreWolf _before_ the updater said it finished updating, you will have a chance to get that error message.

If you don't get any notifications from the updater, then you must have broken Windows' notification system. Did you run anything like O&O ShutUp10 or the likes and set the option "Disable app notifications" by any chance?

**Comment by LiberteIV** [comment]
Hmm 30 seconds is very decemt amount of time.
I'm using the updater since librewolf 102 and it's always been that slow for me.
I'f got a 100 MB/s download and 10 MB/s upload rate.
Downloaded librewolf manually right now and it took me 12 seconds, file size 120 MB.
Yes i did use shutup10 i haven't tought of that my bad, thanks for mentioning this i will enable notification access.
So the notification "mystery" is solved thanks to your suggestion, while download speed is still a bit of a mess.
I really don't know why. I use simplewall and portmaster but i made sure that librewolfwinupdater has full network access, i also had to manually grant permissions to connect to gitlab.com (the download source i guess, same site where i downloaded manually) so that is not any issue..

**Comment by LiberteIV** [comment]
Yeah, i never remember the calculation/value for download/upload rates..

Can confirm now that the notification permission is working after editing shutup10, librewolf winupdater is as fast as downloading the browser from the official site, thanks for the reminder, didn't think of notifications here.

**Comment by ltGuillaume** [comment]
Good to hear everything's in order now! Cheers for the nice words 😄 (and you can buy me a beer if you'd like 😁🙈).
