### ISSUE TITLE
Update Error?

### ISSUE THREAD

**Issue by LiberteIV** [ltGuillaume/LibreWolf-WinUpdater#18]
![Capture](https://user-images.githubusercontent.com/116210112/219904760-0a7cb3eb-1b8d-45c4-919b-81650dfb8abf.PNG)

**Comment by ltGuillaume** [comment]
LibreWolf devs have changed the locatiion for the downloads. Please update to WinUpdater 1.5.1.

**Comment by LiberteIV** [comment]
I should have downloaded the latest updater version you uploaded 40 minutes ago before opening this issue to be honest.
But i was curious why the updater didn't work, i tought that they must have changed the url/link from where the updater get's the files.

So far i know they publish it on librewolf.net and gitlab?

**Comment by ltGuillaume** [comment]
They're finetuning the build process, so it runs on Gitlab itself. Previously the Windows build was generated in a virtual machine and then uploaded. Uploaded files have a different URL from the artifacts generated by Gitlab's CI, I'm guessing.

Since I'm using regular expressions instead of actually using a library to parse JSON, this particular change caused a problem.
