### ISSUE TITLE
codeberg.org

### ISSUE THREAD

**Issue by Abyssgrowth** [ltguillaume/librewolf-winupdater#21]
Just wanted to ask this is you the original author: https://codeberg.org/ltguillaume/librewolf-winupdater
Why move there?

When i klick on the highligted blue URL here https://librewolf.net/installation/windows/ that says "unofficial LibreWolf WinUpdater" that forwards me to coreberg instead of github which previously was the place where i got the updater from.
It's interesting when you said that you hoped to not update the updater anymore and now we are at version 1.6.2 already^

**Comment by ltguillaume** [comment]
Yes, I migrated to Codeberg and am keeping a mirror on GitHub (this one), for the following reasons:

1. I wanted to implement a "self-updating" routine, so that WinUpdater doesn't just fail if the LibreWolf project makes changes in the build process (which has happened several times now). As such, since v1.6.0, WinUpdater first checks if there's a new version of "itself" and updates, before trying to update LibreWolf. I didn't want to do this if it meant that everyone would need to connect to GitHub: people using LibreWolf value their privacy and the policies here are somewhat sketchy at best. As such, update checks are made to Codeberg.org and I set up the Codeberg repo as the primary repo.
2. I have done this with all my repos. I'm keeping the mirrored repos here to make it easier for people not having a Codeberg account to contact me/create issues.

**Comment by Abyssgrowth** [comment]
Thank you for your service!
I've just opened librewolf and the updater scanned for updates, then i used portmaster to see what connections winupdater made, as of now i see both gitlab.com and codeberg.org, i tought you ment that you replaced the gitlab connection with codeberg but this doesn't match with what portmaster shows me, unless i simply missunderstod what you ment.
Pretty sure everyone is thankful for codeberg over gitlab/hub which after all is owned by microsoft.

**Comment by Abyssgrowth** [comment]
![Capture](https://user-images.githubusercontent.com/125774114/233225588-04e013dd-0d20-4caa-824d-f21e5c19d177.PNG)

**Comment by ltguillaume** [comment]
GtHub and GitLab are two separate sites, owned by separate entities. I'm hosting this project on Codeberg and here on GitHub, while LibreWolf is both hosted on GitLab, and built using GitLab's CI.

1. In order to check if there's an internet connection/if Gitlab can be reached at all, a connection is made to GitLab.com
1. In order to check for a new version of WinUpdater, a connection is made to Codeberg.org
1. In order to check for a new version of LibreWolf, a connection is made to GitLab.com
