### ISSUE TITLE
WinUpdater 1.3.4 Error: Application not found 

### ISSUE THREAD

**Issue by ytx2222** [ltGuillaume/LibreWolf-WinUpdater#8]
WinUpdater 1.3.4 Error: Application not found 
![LibreWolfUpdaterError](https://user-images.githubusercontent.com/108699783/177220394-8edede62-e55a-4380-8a38-079e57623dbe.JPG)

**Comment by ltGuillaume** [comment]
The application is trying to run the default browser. Apparently you don't have any browser associated to `https` links?

**Comment by ytx2222** [comment]
No, not from the tray menu, from a explorer window, double clicking LibreWolf-WinUpdater.exe.
Not sure how to associate https links.
Firefox, chrome, brave, opera installed, Win 10

**Comment by ltGuillaume** [comment]
So you're really using https://github.com/ltGuillaume/LibreWolf-WinUpdater/releases/tag/1.3.4, so this very file https://github.com/ltGuillaume/LibreWolf-WinUpdater/releases/download/1.3.4/LibreWolf-WinUpdater_1.3.4.zip? (You didn't compile it yourself, or use the `.ahk` script?)

I'm asking because even if the default browser isn't set correctly on your system, which apparently [does happen](https://www.autohotkey.com/board/topic/27013-failed-attempt-to-launch-with-quick-start-scr/), especially when [using Firefox](https://www.autohotkey.com/board/topic/16478-firefox-as-default-browser-problem-running-url/), this piece of code in the updater shouldn't be triggered at all _unless_ you double click the tray icon.

That being said, you could try this test version and see if it does work for you: 
[LibreWolf-WinUpdater_1.4.0ß.zip](https://github.com/ltGuillaume/LibreWolf-WinUpdater/files/9048496/LibreWolf-WinUpdater_1.4.0ss.zip)

I've added a few lines of code to handle this, so double-clicking the tray icon to open the project's GitHub page should now also work on your system. Could you please test this?

**Comment by ltGuillaume** [comment]
> Yes using https://github.com/ltGuillaume/LibreWolf-WinUpdater/releases/tag/1.3.4 Tried the 1.4.0, It loads your github page if I right click in tray, then select winupdate.

Great, that's solved then with the change. I will make sure it's in the release for 1.4.0.

> I did not have a default browser set, changed it to librefox.

Yeah, at least in part, I suppose. There was a default browser set for *.html files, so v1.4.0 extracts that from the registry and tries to open the GitHub page with that browser. I guess there wasn't a default for https:// URI's on your system, otherwise there would have been no issue.

> But it also says new update available, and says it will update when I close librefox.

The updater waits until the last LibreWolf process is closed. This could be a bit after the moment you closed all LibreWolf windows.

> Then after a really long pause, it asks if I want to install 102.0-2.exe I already have the latest 102.0-2 full installed, so it seems to be a bug.

This is due to the very annoying and imho inconsistent versioning done by LibreWolf. I've already made a step before to improve the updater's handling of this inconsistent versioning, but that only works properly if you let the updater do the updates.

But I've found a way to make this more reliable by reading a different version string from `librewolf.exe`. This should solve it permanently.

> **__UPDATE__** Just tried both 1.3.4 and 1.4.0 again, not getting the update message now, menu tray icon disappears after ~30 seconds, seems to be working. 

Ok, so setting the default browser properly solved the issue with 1.3.4 and having done the update via the updater once has solved the issue of trying to update the already up-to-date installation. Keeping the updater in the tray for a while is intentional, so that the notification remains in the notification center for a while, so you're less likely to miss it.
